spring:
  application:
    name: micro-dept #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.248.24:3306/dept_8001?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useAffectedRows=false&useSSL=false
    username: root
    password: Wuxin123
    dbcp2:
      min-idle: 5
      initial-size: 3
      max-total: 5
      max-wait-millis: 100
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # MyBatis的核心配置文件
  mapper-locations:
    - classpath:mapper/**/*.xml
server:
  port: 8001
eureka: # Eureka注册中心配置
  instance:
    instance-id: dept-server01 #注册id
    lease-expiration-duration-in-seconds: 1 #服务过期时间
    lease-renewal-interval-in-seconds: 1 #服务刷新时间
    ip-address: dept-server01 # 地址
    hostname: dept-server01 # 主机名称
  client:
    service-url:
      defaultZone: http://eureka-server:7001/eureka/
